name: tests

on:
  push:
    paths-ignore:
      - README.md
      - "readme-content/*"
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          pip install -U pip wheel
          sudo apt-get install -y build-essential python3-dev default-libmysqlclient-dev
          pip install -r requirements.txt
      
      - name: Install test dependencies
        run: pip install pytest

      - name: Run tests with Pytest
        run: python -m pytest
